### ISSUE TITLE
Investigate Sentry for error reporting

### ISSUE THREAD

**Issue by welchr** [statgen/locuszoom-api#14]
Right now we have no log monitoring or aggregation for cases when user requests fail. The only monitoring done is whether or not the API is alive and able to respond to requests. 

If users are hitting a common error that should be fixed, we're none the wiser until they report it. 

[Sentry](https://sentry.io/) looks like a nice way to do this. It is free for academic use, and [integrates well with flask](https://docs.sentry.io/clients/python/integrations/flask/).

**Comment by abought** [comment]
+1 for Sentry- I've used it on other projects and it's a real boon. The same instance can define multiple projects; I'd be interested in using this for GfG as well as LZ.org.

It's always free to host your own instance, but indeed, looks like their hosted service is free for academia. Once you have a server it's fairly painless to implement.
https://blog.sentry.io/2015/07/06/free-for-academia

As part of the setup, I might ask whether the academic plan has any usage tier limits. It shouldn't be a problem for LZ, but I could see Genes for Good potentially overrunning the cap during a busy period.

**Comment by welchr** [comment]
I'll shoot them an email regarding the academic license and what the usage limit would be. I think I would prefer using their hosted service if we can (one less thing for us / Sean to have to manage), but if the usage tier is too low then we could try getting a VM up locally to run it. How does that sound?

**Comment by welchr** [comment]
They were kind enough to give us the sponsored plan, which is 500k events/month and no limits on users/projects. Shoot me an email or ping me here if you want to get added to the organization.
