### ISSUE TITLE
UKBB API sends invalid JSON for "infinity" values

### ISSUE THREAD

**Issue by abought** [statgen/locuszoom-api#23]
As captured by Sentry:

UKBB PheWAS plots encounter an error when viewing the following region:
https://portaldev.sph.umich.edu/ukbb/v1/statistic/phewas/?filter=variant%20eq%20%276%3A26093141_G%2FA%27&format=objects&build=GRCh37

This is because Python serializes "inf" values as `Infinity`, which is not compliant with the JSON spec.

Unlike NaNs, I can't find a clear workaround in related python libraries (like SimpleJSON). For lz-hosted, we get around this by translating Infinity to a string, which can be type-coerced on the frontend. See:
https://github.com/statgen/locuszoom-hosted/blob/develop/locuszoom_plotting_service/api/serializers.py#L49

**Comment by welchr** [comment]
Do the null vs. "None" entries cause problems too? Or just the infinity?

**Comment by abought** [comment]
The best source is here:
https://docs.python.org/3/library/json.html#standard-compliance-and-interoperability

Python "None" is OK because JSON has a valid concept of "null". But `NaN` and `Infinity` are not valid JSON, even though python serializes them that way.
